name: Update
on: [ push, pull_request ]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          override: true

      - name: Update page!
        env:
          USER_ID: ${{secrets.USER_ID}}
          USER_TOKEN: ${{secrets.USER_TOKEN}}
        run: cargo run --release -- ./config/config.toml $USER_ID $USER_TOKEN
